name: Build KDMapper
on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Compile Release x64
      run: msbuild kdmapper.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: kdmapper-executable
        path: kdmapper/x64/Release/kdmapper.exe
