name: Generate KDMapper
on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Compile Release x64
      run: msbuild kdmapper.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload Finished File
      uses: actions/upload-artifact@v4
      with:
        name: raw-kdmapper
        path: "**/Release/kdmapper.exe"
